workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    environment:
      flutter: stable
      groups:
        - app_store
      ios_signing:
        provisioning_profiles:
          - SafeBoost AppStore
        certificates:
          - SafeBoost AppStore
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Set up code signing
        script: xcode-project use-profiles --verbose
      - name: Build iOS
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: false

